# Application name
spring:
  application:
    name: api-gate-service

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8181/realms/shov

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/shov
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  # Spring Cloud Gateway Configuration
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**

        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**


      discovery:
        locator:
          enabled: true

# Logging Configuration
logging:
  level:
    root: info                       # Root logger level set to 'info'
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info # Specific logging level for RouteDefinitionLocator
    org.springframework.cloud.gateway: TRACE  # Specific logging level for Spring Cloud Gateway itself

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0