# Server configuration
server:
  port: 8222

# Spring Boot DataSource and JPA configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
  application:
    name: order-service

# Eureka client configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Management endpoint and health configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all endpoints
  endpoint:
    health:
      show-details: always  # Show detailed health information
  health:
    circuitbreakers:
      enabled: true  # Enable circuit breakers

# Zipkin tracing configuration
tracing:
  sampling:
    probability: 1.0  # Set sampling probability to 100% (always trace)

# Resilience4j circuit breaker, time limiter, and retry configuration
resilience4j:
  circuitbreaker:
    instances:
      inventory-service:
        register-health-indicator: true  # Enable health indicator for circuit breaker
        event-consumer-buffer-size: 10
        sliding-window-size: 5
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
#
#  timelimiter:
#    instances:
#      inventory-service:
#        timeout-duration: 3s  # Set the time limit for operations
#
#  retry:
#    instances:
#      inventory-service:
#        max-attempts: 3  # Maximum retry attempts
#        wait-duration: 5s  # Wait duration between retry attempts
