server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory__db
    username: postgres
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  application:
    name: inventory-service
eureka:
  client:
    register-with-client: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka